let num1= 5;
let num2= 7;
let resultado1=Number(num1+num2);
console.log("El resultado de la suma da: ",resultado1);
let resultado2=Number(num1-num2);
console.log("El resultado de la resta da: ",resultado2);
let resultado3=Number(num1*num2);
console.log("El resultado de la multiplicación da: ",resultado3);    
let resultado4=Number(num1/num2);
console.log("El resultado de la división da: ",resultado4);  